In [1]:
import pandas as pd
import os

In [2]:
def load_files(years_load, files_load):
    df = pd.DataFrame()

    for year in years_load:
        for file in files_load:
            fname = "../data/raw/" + file + str(year) + ".csv"

            if os.path.isfile(fname):
                df_tmp = pd.read_csv(
                            fname,
                            encoding="ISO-8859-1",
                            sep=";",
                        )
                
                df_tmp.loc[:, "FILE_NAME"] = file
                
                df = pd.concat([df,df_tmp])
            else:
                print(fname + " not found! Skipping")

    return df

In [3]:
years_load = [2024]
files_load = [
    "itr_cia_aberta_BPA_ind_",
    "itr_cia_aberta_BPP_ind_",
    "itr_cia_aberta_DFC_MD_ind_", 
    "itr_cia_aberta_DFC_MI_ind_", 
    "itr_cia_aberta_DMPL_ind_", 
    "itr_cia_aberta_DRA_ind_", 
    "itr_cia_aberta_DRE_ind_", 
    "itr_cia_aberta_DVA_ind_"
    ]

In [13]:
df = load_files(years_load, files_load)

In [23]:
df_fields = df.copy()
# df_fields = df_fields[df_fields["CD_CVM"] == 20257]
df_fields = df_fields[df_fields["CD_CVM"] == 18376]
df_fields["DS_CONTA"] = df_fields["DS_CONTA"].str.lower()
df_fields = df_fields.groupby(["FILE_NAME","CD_CONTA", "DS_CONTA"]).count().reset_index()
df_fields = df_fields[["FILE_NAME", "CD_CONTA","DS_CONTA"]]
df_fields.head()

,FILE_NAME,CD_CONTA,DS_CONTA
0,itr_cia_aberta_BPA_con_,1,ativo total
1,itr_cia_aberta_BPA_con_,1.01,ativo circulante
2,itr_cia_aberta_BPA_con_,1.01.01,caixa e equivalentes de caixa
3,itr_cia_aberta_BPA_con_,1.01.02,aplicações financeiras
4,itr_cia_aberta_BPA_con_,1.01.02.01,aplicações financeiras avaliadas a valor justo...

In [15]:
df_fields[df_fields["DS_CONTA"].str.contains("receita operacional")]

Empty DataFrame
Columns: [FILE_NAME, CD_CONTA, DS_CONTA]
Index: []

In [16]:
df_fields[df_fields["DS_CONTA"].str.contains("resultado de equivalência patrimonial")]

,FILE_NAME,CD_CONTA,DS_CONTA
195,itr_cia_aberta_DFC_MI_con_,6.01.01.02,resultado de equivalência patrimonial
317,itr_cia_aberta_DRE_con_,3.04.06,resultado de equivalência patrimonial
318,itr_cia_aberta_DRE_con_,3.04.06.01,resultado de equivalência patrimonial
357,itr_cia_aberta_DVA_con_,7.06.01,resultado de equivalência patrimonial

In [17]:
df_fields[df_fields["DS_CONTA"].str.contains("financeiras líquidas")]

Empty DataFrame
Columns: [FILE_NAME, CD_CONTA, DS_CONTA]
Index: []

In [24]:
df_fields[df_fields["DS_CONTA"].str.contains("amortização")]

,FILE_NAME,CD_CONTA,DS_CONTA
205,itr_cia_aberta_DFC_MI_con_,6.01.01.02,depreciação e amortização
364,itr_cia_aberta_DVA_con_,7.04.01,"depreciação, amortização e exaustão"

In [20]:
df_fields[df_fields["DS_CONTA"].str.contains("imposto de renda e contribuição social")]

,FILE_NAME,CD_CONTA,DS_CONTA
43,itr_cia_aberta_BPA_con_,1.02.01.07.01,imposto de renda e contribuição social diferidos
86,itr_cia_aberta_BPP_con_,2.01.03.01.01,imposto de renda e contribuição social a pagar
140,itr_cia_aberta_BPP_con_,2.02.03.01,imposto de renda e contribuição social diferidos
141,itr_cia_aberta_BPP_con_,2.02.03.01.01,imposto de renda e contribuição social diferidos
200,itr_cia_aberta_DFC_MI_con_,6.01.01.06,imposto de renda e contribuição social corrente
201,itr_cia_aberta_DFC_MI_con_,6.01.01.06,imposto de renda e contribuição social correntes
202,itr_cia_aberta_DFC_MI_con_,6.01.01.07,imposto de renda e contribuição social diferidos
225,itr_cia_aberta_DFC_MI_con_,6.01.02.02,imposto de renda e contribuição social pagos
324,itr_cia_aberta_DRE_con_,3.08,imposto de renda e contribuição social sobre o...

In [22]:
df_fields[df_fields["DS_CONTA"].str.contains("lucro")]

,FILE_NAME,CD_CONTA,DS_CONTA
158,itr_cia_aberta_BPP_con_,2.02.06,lucros e receitas a apropriar
159,itr_cia_aberta_BPP_con_,2.02.06.01,lucros a apropriar
174,itr_cia_aberta_BPP_con_,2.03.04,reservas de lucros
178,itr_cia_aberta_BPP_con_,2.03.04.04,reserva de lucros a realizar
179,itr_cia_aberta_BPP_con_,2.03.04.05,reserva de retenção de lucros
186,itr_cia_aberta_BPP_con_,2.03.05,lucros/prejuízos acumulados
194,itr_cia_aberta_DFC_MI_con_,6.01.01.01,lucro líquido do período
273,itr_cia_aberta_DMPL_con_,5.05.01,lucro líquido do período
290,itr_cia_aberta_DRA_con_,4.01,lucro líquido consolidado do período
323,itr_cia_aberta_DRE_con_,3.07,resultado antes dos tributos sobre o lucro
324,itr_cia_aberta_DRE_con_,3.08,imposto de renda e contribuição social sobre o...
329,itr_cia_aberta_DRE_con_,3.10.01,lucro/prejuízo líquido das operações descontin...
331,itr_cia_aberta_DRE_con_,3.11,lucro/prejuízo consolidado do período
334,itr_cia_aberta_DRE_con_,3.99,lucro por ação - (reais / ação)
335,itr_cia_aberta_DRE_con_,3.99.01,lucro básico por ação
338,itr_cia_aberta_DRE_con_,3.99.02,lucro diluído por ação
383,itr_cia_aberta_DVA_con_,7.08.04.03,lucros retidos / prejuízo do período
384,itr_cia_aberta_DVA_con_,7.08.04.04,part. não controladores nos lucros retidos