In [2]:
import pandas as pd
import os

In [8]:
def load_files(years_load, files_load):
    df = pd.DataFrame()

    for year in years_load:
        for file in files_load:
            fname = "../data/raw/" + file + str(year) + ".csv"

            if os.path.isfile(fname):
                df_tmp = pd.read_csv(
                            fname,
                            encoding="ISO-8859-1",
                            sep=";",
                        )
                
                df_tmp.loc[:, "FILE_NAME"] = file + str(year)
                
                df = pd.concat([df,df_tmp])
            else:
                print(fname + " not found! Skipping")

    return df

In [9]:
years_load = [2019, 2020, 2021, 2022, 2023, 2024]
files_load = [
    # "itr_cia_aberta_BPA_ind_",
    # "itr_cia_aberta_BPP_ind_",
    # "itr_cia_aberta_DFC_MD_ind_", 
    # "itr_cia_aberta_DFC_MI_ind_", 
    # "itr_cia_aberta_DMPL_ind_", 
    # "itr_cia_aberta_DRA_ind_", 
    "itr_cia_aberta_DRE_ind_", 
    "dfp_cia_aberta_DRE_ind_", 
    # "itr_cia_aberta_DVA_ind_"
    ]

In [10]:
df = load_files(years_load, files_load)

In [31]:
df_fields = df.copy()
df_fields = df_fields[df_fields["CD_CVM"] == 1023]
df_fields["DS_CONTA"] = df_fields["DS_CONTA"].str.lower()
df_fields = df_fields.groupby(["FILE_NAME","CD_CONTA", "DS_CONTA"]).count().reset_index()
df_fields = df_fields[["FILE_NAME", "CD_CONTA","DS_CONTA"]]
df_fields.head()

                     FILE_NAME CD_CONTA                              DS_CONTA
0  dfp_cia_aberta_DRE_ind_2019     3.01  receitas da intermediação financeira
1  dfp_cia_aberta_DRE_ind_2019  3.01.01                  operações de crédito
2  dfp_cia_aberta_DRE_ind_2019  3.01.02   operações de arrendamento mercantil
3  dfp_cia_aberta_DRE_ind_2019  3.01.03        resultado de operações com tvm
4  dfp_cia_aberta_DRE_ind_2019  3.01.04                      resultado de ifd

In [34]:
df_fields[ \
    df_fields["DS_CONTA"].str.contains("lucro") \
    & df_fields["DS_CONTA"].str.contains("prejuízo")]\
        .groupby(["CD_CONTA", "DS_CONTA"]).count().reset_index()

  CD_CONTA                                           DS_CONTA  FILE_NAME
0     3.07        lucro ou prejuízo das operações continuadas          8
1     3.09  lucro ou prejuízo antes das participações e co...          8
2     3.11               lucro ou prejuízo líquido do período          8
3     3.13                          lucro/prejuízo do período          3

In [33]:
kpis = ["lucro ou prejuízo líquido do período", "lucro/prejuízo do período"]
df_fields[df_fields["DS_CONTA"].isin(kpis)]

,FILE_NAME,CD_CONTA,DS_CONTA
37,dfp_cia_aberta_DRE_ind_2019,3.13,lucro/prejuízo do período
75,dfp_cia_aberta_DRE_ind_2020,3.11,lucro ou prejuízo líquido do período
116,dfp_cia_aberta_DRE_ind_2021,3.11,lucro ou prejuízo líquido do período
157,dfp_cia_aberta_DRE_ind_2022,3.11,lucro ou prejuízo líquido do período
198,dfp_cia_aberta_DRE_ind_2023,3.11,lucro ou prejuízo líquido do período
244,itr_cia_aberta_DRE_ind_2019,3.13,lucro/prejuízo do período
282,itr_cia_aberta_DRE_ind_2020,3.13,lucro/prejuízo do período
321,itr_cia_aberta_DRE_ind_2021,3.11,lucro ou prejuízo líquido do período
362,itr_cia_aberta_DRE_ind_2022,3.11,lucro ou prejuízo líquido do período
403,itr_cia_aberta_DRE_ind_2023,3.11,lucro ou prejuízo líquido do período
444,itr_cia_aberta_DRE_ind_2024,3.11,lucro ou prejuízo líquido do período