In [1]:
import pandas as pd
import datetime

In [2]:
dfp_dre_2022 = pd.read_csv("../data/raw/dfp_cia_aberta_DRE_con_2022.csv", encoding = "ISO-8859-1", sep=";")
dfp_dre_2023 = pd.read_csv("../data/raw/dfp_cia_aberta_DRE_con_2023.csv", encoding = "ISO-8859-1", sep=";")

itr_dre_2022 = pd.read_csv("../data/raw/itr_cia_aberta_DRE_con_2022.csv", encoding = "ISO-8859-1", sep=";")
itr_dre_2023 = pd.read_csv("../data/raw/itr_cia_aberta_DRE_con_2023.csv", encoding = "ISO-8859-1", sep=";")
itr_dre_2024 = pd.read_csv("../data/raw/itr_cia_aberta_DRE_con_2024.csv", encoding = "ISO-8859-1", sep=";")
df = pd.concat([itr_dre_2022, dfp_dre_2022, itr_dre_2023, dfp_dre_2023, itr_dre_2024])

In [3]:
df.head()

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2021-01-01,2021-03-31,3.01,Receitas de Intermediação Financeira,23354279.0,S
1,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-01-01,2022-03-31,3.01,Receitas de Intermediação Financeira,48490439.0,S
2,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2021-01-01,2021-03-31,3.01.01,Receita de Juros,23354279.0,N
3,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2022-01-01,2022-03-31,3.01.01,Receita de Juros,48490439.0,N
4,00.000.000/0001-91,2022-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2021-01-01,2021-03-31,3.02,Despesas de Intermediação Financeira,-9590313.0,S

In [4]:
df["DT_FIM_EXERC"] = pd.to_datetime(df["DT_FIM_EXERC"])
df["DT_INI_EXERC"] = pd.to_datetime(df["DT_INI_EXERC"])
df["EXERC_YEAR"] = df["DT_INI_EXERC"].dt.year

In [5]:
df_bbas3 = df[df["CD_CVM"] == 1023]
df_bbas3 = df_bbas3[df_bbas3["ORDEM_EXERC"] == "ÚLTIMO"]
df_bbas3["DS_CONTA"].unique()

array(['Receitas de Intermediação Financeira', 'Receita de Juros',
       'Despesas de Intermediação Financeira', 'Despesa de Juros',
       'Resultado Bruto de Intermediação Financeira',
       'Outras Despesas e Receitas Operacionais',
       'Despesa de Provisão para Perda Esperada para Risco de Crédito',
       'Receitas de Prestação de Serviços', 'Despesas com Pessoal',
       'Outras Despesas de Administrativas', 'Despesas Tributárias',
       'Outras Receitas Operacionais',
       'Ganhos/(perdas) líquidos sobre instrumentos financeiros',
       'Resultado líquido em operações de câmbio e em conversão de transações em moedas estrangeiras',
       'Outras', 'Outras Despesas Operacionais',
       'Amortização de ativos intangíveis',
       'Provisões trabalhistas, fiscais e cíveis', 'Depreciação',
       'Resultado da Equivalência Patrimonial',
       'Resultado antes dos Tributos sobre o Lucro',
       'Imposto de Renda e Contribuição Social sobre o Lucro', 'Corrente',
       'Diferido', 'Lucro ou Prejuízo das Operações Continuadas',
       'Resultado Líquido das Operações Descontinuadas',
       'Lucro ou Prejuízo antes das Participações e Contribuições Estatutárias',
       'Participações nos Lucros e Contribuições Estatutárias',
       'Lucro ou Prejuízo Líquido Consolidado do Período',
       'Atribuído aos Sócios da Empresa Controladora',
       'Atribuído aos Sócios não Controladores',
       'Lucro por Ação (R$/Ação)', 'Lucro Básico por Ação', 'ON',
       'Lucro Diluído por Ação',
       'Ganhos líquidos sobre instrumentos financeiros'], dtype=object)

In [6]:
kips = [
    "Lucro ou Prejuízo Líquido Consolidado do Período",
    ]

disp_columns = ["EXERC_YEAR", "DT_INI_EXERC", "DT_FIM_EXERC", "DS_CONTA", "VL_CONTA"]

df_bbas3[df_bbas3["DS_CONTA"].isin(kips)][disp_columns]

,EXERC_YEAR,DT_INI_EXERC,DT_FIM_EXERC,DS_CONTA,VL_CONTA
59,2022,2022-01-01,2022-03-31,Lucro ou Prejuízo Líquido Consolidado do Período,4974664.0
192,2022,2022-01-01,2022-06-30,Lucro ou Prejuízo Líquido Consolidado do Período,13695840.0
193,2022,2022-04-01,2022-06-30,Lucro ou Prejuízo Líquido Consolidado do Período,8721176.0
340,2022,2022-01-01,2022-09-30,Lucro ou Prejuízo Líquido Consolidado do Período,21779414.0
341,2022,2022-07-01,2022-09-30,Lucro ou Prejuízo Líquido Consolidado do Período,8083574.0
59,2022,2022-01-01,2022-12-31,Lucro ou Prejuízo Líquido Consolidado do Período,29849335.0
59,2023,2023-01-01,2023-03-31,Lucro ou Prejuízo Líquido Consolidado do Período,7290982.0
192,2023,2023-01-01,2023-06-30,Lucro ou Prejuízo Líquido Consolidado do Período,16383496.0
193,2023,2023-04-01,2023-06-30,Lucro ou Prejuízo Líquido Consolidado do Período,9092514.0
340,2023,2023-01-01,2023-09-30,Lucro ou Prejuízo Líquido Consolidado do Período,25225143.0
341,2023,2023-07-01,2023-09-30,Lucro ou Prejuízo Líquido Consolidado do Período,8841647.0
59,2023,2023-01-01,2023-12-31,Lucro ou Prejuízo Líquido Consolidado do Período,33165591.0
59,2024,2024-01-01,2024-03-31,Lucro ou Prejuízo Líquido Consolidado do Período,8680714.0
192,2024,2024-01-01,2024-06-30,Lucro ou Prejuízo Líquido Consolidado do Período,18165943.0
193,2024,2024-04-01,2024-06-30,Lucro ou Prejuízo Líquido Consolidado do Período,9485229.0

In [7]:
td_quarter = datetime.timedelta(days=93)
td_year = datetime.timedelta(days=360)

profit_raw = df_bbas3[df_bbas3["DS_CONTA"].isin(kips)]
dt_diff = profit_raw["DT_FIM_EXERC"] - profit_raw["DT_INI_EXERC"]

profit_quarter = profit_raw[dt_diff <= td_quarter]
profit_quarter_grouped = profit_quarter.groupby("EXERC_YEAR").agg({"VL_CONTA": "sum", "DT_FIM_EXERC": "max"}).reset_index()

profit_year = profit_raw[dt_diff >= td_year]
profit_year = pd.merge(profit_year, profit_quarter_grouped, how="inner", on="EXERC_YEAR", suffixes=("_year", "_quarters"))
profit_year["VL_CONTA"] = profit_year["VL_CONTA_year"] - profit_year["VL_CONTA_quarters"]
profit_year["DT_INI_EXERC"] = profit_year["DT_FIM_EXERC_quarters"] + datetime.timedelta(days=1)
profit_year = profit_year.rename({"DT_FIM_EXERC_year": "DT_FIM_EXERC"}, axis=1)
profit_year = profit_year.drop(["VL_CONTA_year", "VL_CONTA_quarters", "DT_FIM_EXERC_quarters"], axis=1)

profit_quarter = pd.concat([profit_quarter, profit_year]).sort_values(by="DT_INI_EXERC").reset_index()

In [8]:
profit_quarter[disp_columns]

,EXERC_YEAR,DT_INI_EXERC,DT_FIM_EXERC,DS_CONTA,VL_CONTA
0,2022,2022-01-01,2022-03-31,Lucro ou Prejuízo Líquido Consolidado do Período,4974664.0
1,2022,2022-04-01,2022-06-30,Lucro ou Prejuízo Líquido Consolidado do Período,8721176.0
2,2022,2022-07-01,2022-09-30,Lucro ou Prejuízo Líquido Consolidado do Período,8083574.0
3,2022,2022-10-01,2022-12-31,Lucro ou Prejuízo Líquido Consolidado do Período,8069921.0
4,2023,2023-01-01,2023-03-31,Lucro ou Prejuízo Líquido Consolidado do Período,7290982.0
5,2023,2023-04-01,2023-06-30,Lucro ou Prejuízo Líquido Consolidado do Período,9092514.0
6,2023,2023-07-01,2023-09-30,Lucro ou Prejuízo Líquido Consolidado do Período,8841647.0
7,2023,2023-10-01,2023-12-31,Lucro ou Prejuízo Líquido Consolidado do Período,7940448.0
8,2024,2024-01-01,2024-03-31,Lucro ou Prejuízo Líquido Consolidado do Período,8680714.0
9,2024,2024-04-01,2024-06-30,Lucro ou Prejuízo Líquido Consolidado do Período,9485229.0