In [1]:
import pandas as pd
import yfinance as yf

In [17]:
###Building the ticker for yfinance
df = pd.read_csv("../data/processed/stocks-basic-info.csv")

def get_main_ticker(tickers):
    tickers = tickers.split(";")
    
    for ticker in tickers:
        if ticker[4] == "4": return ticker
        
    for ticker in tickers:
        if ticker[4] == "3": return ticker
        
    return tickers[0]

def get_yf_ticker(tickers):
    ticker = get_main_ticker(tickers)
    return ticker + ".SA"

In [83]:
tickers = df["TICKERS"].iloc[1]

bbas3 = yf.Ticker(get_yf_ticker(tickers))

In [77]:
# get all stock info
bbas3.info

{'address1': 'Cidade De Deus, S/N',
 'address2': 'Vila Yara',
 'city': 'Osasco',
 'state': 'SP',
 'zip': '06029-900',
 'country': 'Brazil',
 'phone': '55 80 0704 8383',
 'website': 'https://banco.bradesco',
 'industry': 'Banks - Regional',
 'industryKey': 'banks-regional',
 'industryDisp': 'Banks - Regional',
 'sector': 'Financial Services',
 'sectorKey': 'financial-services',
 'sectorDisp': 'Financial Services',
 'longBusinessSummary': 'Banco Bradesco S.A., together with its subsidiaries, provides various banking products and services to individuals, corporates, and businesses in Brazil and internationally. The company operates through two segments, Banking and Insurance. It provides current, savings, click, and salary accounts; real estate credit, vehicle financing, payroll loans, mortgage loans, microcredit, leasing, and personal and installment credit; overdraft and agribusiness loans; debit and business cards; financial and security services; consortium products; car, personal accident, dental, travel, and life insurance; investment products; pension products; foreign currency exchange services; capitalization bonds; and internet banking services. Banco Bradesco S.A. was founded in 1943 and is headquartered in Osasco, Brazil.',
 'fullTimeEmployees': 84711,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Marcelo  de Araujo Noronha',
   'age': 58,
   'title': 'CEO & Member of Executive Board',
   'yearBorn': 1965,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Cassiano Ricardo Scarpelli',
   'age': 55,
   'title': 'CFO, Executive VP of Director & Member of Executive Board',
   'yearBorn': 1968,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Moacir  Nachbar Jr., Junior',
   'age': 58,
   'title': 'Executive VP of Director, Chief Risk Officer & Member of Executive Board',
   'yearBorn': 1965,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Antonio Jose da Barbara',
   'age': 55,
   'title': 'Managing Executive Officer &  Member of Executive Board',
   'yearBorn': 1968,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jose Ramos Rocha Neto',
   'age': 55,
   'title': 'Executive VP & Member of the Executive Board',
   'yearBorn': 1968,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Joao Carlos Gomes da Silva',
   'age': 62,
   'title': 'Executive Officer & Member of Board of Executive Officers',
   'yearBorn': 1961,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Eurico Ramos Fabri',
   'age': 51,
   'title': 'Executive VP of Director & Member of Executive Board',
   'yearBorn': 1972,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Guilherme Muller Leal',
   'age': 56,
   'title': 'Executive VP & Member of Executive Board',
   'yearBorn': 1967,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Roberto  de Jesus Paris',
   'age': 51,
   'title': 'Executive Officer & Member of Executive Board',
   'yearBorn': 1972,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Rogerio Pedro Camara',
   'age': 60,
   'title': 'Executive VP Director, Member of Executive Board & Director',
   'yearBorn': 1963,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 1,
 'boardRisk': 6,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 10,
 'overallRisk': 7,
 'governanceEpochDate': 1727740800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 15.04,
 'open': 14.93,
 'dayLow': 14.9,
 'dayHigh': 15.31,
 'regularMarketPreviousClose': 15.04,
 'regularMarketOpen': 14.93,
 'regularMarketDayLow': 14.9,
 'regularMarketDayHigh': 15.31,
 'dividendRate': 0.78,
 'dividendYield': 0.0519,
 'exDividendDate': 1730678400,
 'payoutRatio': 0.7168,
 'fiveYearAvgDividendYield': 4.6,
 'beta': 0.653,
 'trailingPE': 12.871796,
 'forwardPE': 6.5764194,
 'volume': 23619600,
 'regularMarketVolume': 23619600,
 'averageVolume': 36187587,
 'averageVolume10days': 41059070,
 'averageDailyVolume10Day': 41059070,
 'bid': 15.06,
 'ask': 15.09,
 'marketCap': 150355132416,
 'fiftyTwoWeekLow': 12.14,
 'fiftyTwoWeekHigh': 17.74,
 'priceToSalesTrailing12Months': 2.1626675,
 'fiftyDayAverage': 14.892,
 'twoHundredDayAverage': 14.1224,
 'trailingAnnualDividendRate': 0.057,
 'trailingAnnualDividendYield': 0.0037898936,
 'currency': 'BRL',
 'enterpriseValue': 592865722368,
 'profitMargins': 0.18802999,
 'floatShares': 7555873919,
 'sharesOutstanding': 5295830016,
 'heldPercentInsiders': 0.022850001,
 'heldPercentInstitutions': 0.2845,
 'impliedSharesOutstanding': 10433300480,
 'bookValue': 15.57,
 'priceToBook': 0.96724474,
 'lastFiscalYearEnd': 1703980800,
 'nextFiscalYearEnd': 1735603200,
 'mostRecentQuarter': 1719705600,
 'earningsQuarterlyGrowth': 0.025,
 'netIncomeToCommon': 13072209920,
 'trailingEps': 1.17,
 'forwardEps': 2.29,
 'pegRatio': 2.43,
 'lastSplitFactor': '11:10',
 'lastSplitDate': 1650326400,
 'enterpriseToRevenue': 8.528,
 '52WeekChange': 0.050209165,
 'SandP52WeekChange': 0.32645774,
 'lastDividendValue': 0.018975,
 'lastDividendDate': 1733184000,
 'exchange': 'SAO',
 'quoteType': 'EQUITY',
 'symbol': 'BBDC4.SA',
 'underlyingSymbol': 'BBDC4.SA',
 'shortName': 'BRADESCO    PN      N1',
 'longName': 'Banco Bradesco S.A.',
 'firstTradeDateEpochUtc': 1199275200,
 'timeZoneFullName': 'America/Sao_Paulo',
 'timeZoneShortName': 'BRT',
 'uuid': '77616a7b-39fb-34f4-a147-dc57405a18da',
 'messageBoardId': 'finmb_877263',
 'gmtOffSetMilliseconds': -10800000,
 'currentPrice': 15.06,
 'targetHighPrice': 18.0,
 'targetLowPrice': 14.0,
 'targetMeanPrice': 15.56,
 'targetMedianPrice': 15.66,
 'recommendationMean': 2.8,
 'recommendationKey': 'hold',
 'numberOfAnalystOpinions': 12,
 'totalCash': 263017562112,
 'totalCashPerShare': 24.874,
 'totalDebt': 696119853056,
 'totalRevenue': 69522997248,
 'revenuePerShare': 6.539,
 'returnOnAssets': 0.0069,
 'returnOnEquity': 0.08035,
 'operatingCashflow': -114811289600,
 'earningsGrowth': 0.027,
 'revenueGrowth': 0.096,
 'operatingMargins': 0.246,
 'financialCurrency': 'BRL',
 'trailingPegRatio': 0.4635}

In [78]:
# get historical market data
hist = bbas3.history(period="2y")

In [79]:
hist_clean = hist[["Close", "Dividends"]]
hist_clean["Dividends_1y"] = hist_clean["Dividends"].rolling('365D').sum()
hist_clean = hist_clean.reset_index()
hist_clean["Date"] = hist_clean["Date"].dt.date
hist_clean["Dividend_Yield"] = hist_clean["Dividends_1y"] / hist_clean["Close"]
hist_clean

/tmp/ipykernel_13543/3496808065.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hist_clean["Dividends_1y"] = hist_clean["Dividends"].rolling('365D').sum()

           Date      Close  Dividends  Dividends_1y  Dividend_Yield
0    2022-10-04  18.436129   0.018974      0.018974        0.001029
1    2022-10-05  18.636333   0.000000      0.018974        0.001018
2    2022-10-06  18.253338   0.000000      0.018974        0.001039
3    2022-10-07  17.818110   0.000000      0.018974        0.001065
4    2022-10-10  17.548267   0.000000      0.018974        0.001081
..          ...        ...        ...           ...             ...
497  2024-09-30  14.483739   0.000000      0.819652        0.056591
498  2024-10-01  14.671024   0.197528      1.017180        0.069333
499  2024-10-02  15.200000   0.018975      1.017180        0.066920
500  2024-10-03  15.040000   0.000000      1.017180        0.067632
501  2024-10-04  15.060000   0.000000      1.017180        0.067542

[502 rows x 5 columns]

In [80]:
bbas3.history_metadata

{'currency': 'BRL',
 'symbol': 'BBDC4.SA',
 'exchangeName': 'SAO',
 'fullExchangeName': 'São Paulo',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 1199275200,
 'regularMarketTime': 1728072467,
 'hasPrePostMarketData': False,
 'gmtoffset': -10800,
 'timezone': 'BRT',
 'exchangeTimezoneName': 'America/Sao_Paulo',
 'regularMarketPrice': 15.06,
 'fiftyTwoWeekHigh': 15.31,
 'fiftyTwoWeekLow': 14.9,
 'regularMarketDayHigh': 15.31,
 'regularMarketDayLow': 14.9,
 'regularMarketVolume': 23619600,
 'longName': 'Banco Bradesco S.A.',
 'shortName': 'BRADESCO    PN      N1',
 'chartPreviousClose': 21.18,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'BRT',
   'start': 1728045900,
   'end': 1728046800,
   'gmtoffset': -10800},
  'regular': {'timezone': 'BRT',
   'start': 1728046800,
   'end': 1728072000,
   'gmtoffset': -10800},
  'post': {'timezone': 'BRT',
   'start': 1728072000,
   'end': 1728075600,
   'gmtoffset': -10800}},
 'dataGranularity': '1d',
 'range': '2y',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [22]:
bbas3.actions

                           Dividends  Stock Splits
Date
2014-11-17 00:00:00-02:00   0.027859           0.0
2014-12-12 00:00:00-02:00   0.169975           0.0
2015-02-20 00:00:00-02:00   0.045600           0.0
2015-03-24 00:00:00-03:00   0.188496           0.0
2015-05-22 00:00:00-03:00   0.225569           0.0
...                              ...           ...
2024-04-16 00:00:00-03:00   0.000000           2.0
2024-06-12 00:00:00-03:00   0.457947           0.0
2024-06-14 00:00:00-03:00   0.204240           0.0
2024-08-22 00:00:00-03:00   0.474655           0.0
2024-09-12 00:00:00-03:00   0.186602           0.0

[78 rows x 2 columns]

In [75]:
bbas3.dividends

Date
2022-11-22 00:00:00-03:00    0.085103
2022-12-13 00:00:00-03:00    0.172763
2023-02-24 00:00:00-03:00    0.413441
2023-03-14 00:00:00-03:00    0.176018
2023-06-02 00:00:00-03:00    0.061504
2023-06-13 00:00:00-03:00    0.169316
2023-08-22 00:00:00-03:00    0.073423
2023-09-12 00:00:00-03:00    0.167099
2023-12-12 00:00:00-03:00    0.171153
2024-03-12 00:00:00-03:00    0.205018
2024-06-12 00:00:00-03:00    0.457947
2024-06-14 00:00:00-03:00    0.204240
2024-08-22 00:00:00-03:00    0.474655
2024-09-12 00:00:00-03:00    0.186602
Name: Dividends, dtype: float64

In [24]:
bbas3.splits

Date
2024-04-16 00:00:00-03:00    2.0
Name: Stock Splits, dtype: float64

In [81]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [85]:
tk = get_main_ticker(tickers)
url = "https://www.dadosdemercado.com.br/acoes/" + tk + "/dividendos"
page = requests.get(url)

soup = BeautifulSoup(page.content, "html.parser")

In [117]:
cells = soup \
    .find(class_="table-container") \
    .find_all("td")
    
df_dividends = pd.DataFrame()
    
for row_idx in range(int(len(cells) / 5)):
    row_start = row_idx * 5
    row_end = row_start + 5
    row = cells[row_start : row_end]
    
    dividend = pd.DataFrame(
        {
        "DATE": row[2].text, 
        "VALUE": float(row[1].text.replace("*", "").replace(",", ".")), 
        "TYPE": row[0].text
        },
        index=[df_dividends.shape[0]]
        )
    
    df_dividends = pd.concat([df_dividends, dividend])
    
df_dividends["DATE"] = pd.to_datetime(df_dividends["DATE"], format="%d/%m/%Y")
df_dividends

          DATE     VALUE       TYPE
0   2024-09-11  0.186602        JCP
1   2024-08-21  0.314481        JCP
2   2024-08-21  0.151861  Dividendo
3   2024-08-21  0.005606  Dividendo
4   2024-08-21  0.002707  Dividendo
..         ...       ...        ...
156 2007-12-25  0.071121        JCP
157 2007-11-13  0.042861  Dividendo
158 2007-09-21  0.067322        JCP
159 2007-08-14  0.019767  Dividendo
160 2007-06-21  0.066809        JCP

[161 rows x 3 columns]