In [1]:
import pandas as pd

In [8]:
df = pd.read_csv("../data/raw/cad_cia_aberta.csv", encoding = "ISO-8859-1", sep=";")

In [9]:
df.head()

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
0,08.773.135/0001-00,2W ECOBANK S.A.,2W ECOBANK S.A.,2020-10-29,2007-03-23,NaN,NaN,ATIVO,2020-10-29,25224,...,NaN,NaN,4711130.0,11,39574900.0,NaN,NaN,juridico@2wecobank.com.br,52.803.244/0001-06,KPMG AUDITORES ASSOCIADOS
1,11.396.633/0001-87,3A COMPANHIA SECURITIZADORA,TRIPLO A COMPANHIA SECURITIZADORA,2010-03-08,2009-11-03,2015-12-18,Cancelamento Voluntário - IN CVM 480/09,CANCELADA,2015-12-18,21954,...,RJ,NaN,20020000.0,21,22338867.0,21.0,22338867.0,juridico@triploasec.com.br,60.525.706/0001-07,MOORE STEPHENS LIMA LUCCHESI AUDITORES INDEPEN...
2,12.091.809/0001-55,3R PETROLEUM OLÉO E GÁS S.A.,NaN,2020-11-09,2010-06-08,NaN,NaN,ATIVO,2020-11-09,25291,...,NaN,NaN,22250145.0,21,34755555.0,NaN,NaN,ri@bravaenergia.com,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.
3,01.547.749/0001-16,521 PARTICIPAÇOES S.A. - EM LIQUIDAÇÃO EXTRAJU...,521 PARTICIPAÇÕES S/A,1997-07-11,1996-07-30,NaN,NaN,ATIVO,1997-07-11,16330,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.859.935/0001-70,BAKER TILLY BRASIL RJ AUDITORES INDEPENDENTES ...
4,01.851.771/0001-55,524 PARTICIPAÇOES SA,524 PARTICIPACOES SA,1997-05-30,1997-04-02,NaN,NaN,ATIVO,1997-05-30,16284,...,RJ,NaN,20020010.0,21,38043700.0,NaN,NaN,gar@opportunity.com.br,40.262.602/0001-31,"BKR - LOPES, MACHADO AUDITORES"

In [10]:
df.columns

Index(['CNPJ_CIA', 'DENOM_SOCIAL', 'DENOM_COMERC', 'DT_REG', 'DT_CONST',
       'DT_CANCEL', 'MOTIVO_CANCEL', 'SIT', 'DT_INI_SIT', 'CD_CVM',
       'SETOR_ATIV', 'TP_MERC', 'CATEG_REG', 'DT_INI_CATEG', 'SIT_EMISSOR',
       'DT_INI_SIT_EMISSOR', 'CONTROLE_ACIONARIO', 'TP_ENDER', 'LOGRADOURO',
       'COMPL', 'BAIRRO', 'MUN', 'UF', 'PAIS', 'CEP', 'DDD_TEL', 'TEL',
       'DDD_FAX', 'FAX', 'EMAIL', 'TP_RESP', 'RESP', 'DT_INI_RESP',
       'LOGRADOURO_RESP', 'COMPL_RESP', 'BAIRRO_RESP', 'MUN_RESP', 'UF_RESP',
       'PAIS_RESP', 'CEP_RESP', 'DDD_TEL_RESP', 'TEL_RESP', 'DDD_FAX_RESP',
       'FAX_RESP', 'EMAIL_RESP', 'CNPJ_AUDITOR', 'AUDITOR'],
      dtype='object')

In [11]:
df[df["CNPJ_CIA"] ==  "00.000.000/0001-91"]

,CNPJ_CIA,DENOM_SOCIAL,DENOM_COMERC,DT_REG,DT_CONST,DT_CANCEL,MOTIVO_CANCEL,SIT,DT_INI_SIT,CD_CVM,...,UF_RESP,PAIS_RESP,CEP_RESP,DDD_TEL_RESP,TEL_RESP,DDD_FAX_RESP,FAX_RESP,EMAIL_RESP,CNPJ_AUDITOR,AUDITOR
245,00.000.000/0001-91,BANCO DO BRASIL S.A.,BANCO DO BRASIL S.A.,1977-07-20,1905-12-30,NaN,NaN,ATIVO,1977-07-20,1023,...,DF,NaN,70040912.0,61,34935602.0,NaN,NaN,dribb@bb.com.br,57.755.217/0001-29,KPMG AUDITORES INDEPENDENTES LTDA.

In [19]:
columns = ["DENOM_SOCIAL", "SETOR_ATIV", "CD_CVM", "CNPJ_CIA", "CONTROLE_ACIONARIO", "SIT"]
df[df["CNPJ_CIA"] ==  "00.000.000/0001-91"][columns]

,DENOM_SOCIAL,SETOR_ATIV,CD_CVM,CNPJ_CIA,CONTROLE_ACIONARIO,SIT
245,BANCO DO BRASIL S.A.,Bancos,1023,00.000.000/0001-91,ESTATAL,ATIVO