In [1]:
import pandas as pd
import yfinance as yf

In [2]:
cmig = yf.Ticker('AMBP3.SA')

In [7]:
hist1 = cmig.history(period="10y", interval="1wk")
hist1.shape[0]
# hist2 = cmig.history(period="5d")
# pd.concat([hist1, hist2]).tail(10).drop_duplicates()

AMBP3.SA: Period '10y' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', '5y', 'ytd', 'max']

0

In [14]:
pd.concat([hist1, hist2]).reset_index().tail(10).drop_duplicates()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
257,2024-09-23 00:00:00-03:00,11.335228,11.463365,11.098667,11.157806,56707700,0.165202,0.0
258,2024-09-30 00:00:00-03:00,11.320000,11.650000,11.110000,11.160000,45876300,0.000000,0.0
259,2024-10-07 00:00:00-03:00,11.220000,11.320000,10.930000,11.020000,48846000,0.000000,0.0
260,2024-10-14 00:00:00-03:00,11.020000,11.230000,10.950000,11.040000,69240600,0.000000,0.0
261,2024-10-21 00:00:00-03:00,11.050000,11.140000,10.990000,11.030000,7775300,0.000000,0.0
262,2024-10-16 00:00:00-03:00,11.130000,11.230000,11.030000,11.150000,13196600,0.000000,0.0
263,2024-10-17 00:00:00-03:00,11.080000,11.160000,11.000000,11.100000,7091500,0.000000,0.0
264,2024-10-18 00:00:00-03:00,11.170000,11.200000,10.950000,11.040000,18503600,0.000000,0.0
265,2024-10-21 00:00:00-03:00,11.050000,11.140000,11.000000,11.120000,7216700,0.000000,0.0
266,2024-10-22 00:00:00-03:00,11.060000,11.080000,10.990000,11.030000,558600,0.000000,0.0

In [6]:
cmig.get_shares_full()

AttributeError: 'Ticker' object has no attribute 'get_prices'

In [15]:
cmig.quarterly_income_stmt

,2024-03-31,2023-12-31,2023-09-30,2023-06-30,2023-03-31
Tax Effect Of Unusual Items,4652783.743955,21797423.280785,20602126.975813,37809190.366832,-3167997.448943
Tax Rate For Calcs,0.232279,0.058117,0.163781,0.229095,0.20257
Normalized EBITDA,2209906000.0,1529017000.0,2558853000.0,2019052000.0,2507728000.0
Total Unusual Items,20031000.0,375059000.0,125791000.0,165037000.0,-15639000.0
Total Unusual Items Excluding Goodwill,20031000.0,375059000.0,125791000.0,165037000.0,-15639000.0
Net Income From Continuing Operation Net Minority Interest,1152891000.0,1884472000.0,1237307000.0,1244683000.0,1398206000.0
Reconciled Depreciation,329000000.0,-256698000.0,923000000.0,304698000.0,303000000.0
Reconciled Cost Of Revenue,5813524000.0,8299594000.0,6157501000.0,6499389000.0,5491231000.0
EBITDA,2229937000.0,1904076000.0,2684644000.0,2184089000.0,2492089000.0
EBIT,1900937000.0,2160774000.0,1761644000.0,1879391000.0,2189089000.0
Net Interest Income,-180986000.0,-182721000.0,-295000000.0,-125375000.0,-105914000.0
Interest Expense,399231000.0,158290000.0,282000000.0,263910000.0,435698000.0
Interest Income,218245000.0,NaN,NaN,215951000.0,329784000.0
Normalized Income,1137512783.743955,1531210423.280785,1132118126.975813,1117455190.366832,1410677002.551057
Net Income From Continuing And Discontinued Operation,1152891000.0,1884472000.0,1237307000.0,1244683000.0,1398206000.0
Total Expenses,7357082000.0,8287873000.0,7848840000.0,7313462000.0,6790268000.0
Total Operating Income As Reported,NaN,NaN,NaN,1575671000.0,NaN
Diluted Average Shares,2860681881.0,2860681881.0,2860681881.0,2838750702.0,2860681881.0
Basic Average Shares,2860681881.0,2860681881.0,2860681881.0,2838750702.0,2860681881.0
Diluted EPS,0.403013,0.659283,0.432522,0.438462,0.488767
Basic EPS,0.403013,0.659283,0.432522,0.438462,0.488767
Diluted NI Availto Com Stockholders,1152891000.0,1884472000.0,1237307000.0,1244683000.0,1398206000.0
Net Income Common Stockholders,1152891000.0,1884472000.0,1237307000.0,1244683000.0,1398206000.0
Net Income,1152891000.0,1884472000.0,1237307000.0,1244683000.0,1398206000.0
Minority Interests,NaN,NaN,NaN,-699000.0,NaN
Net Income Including Noncontrolling Interests,1152891000.0,1886105000.0,1237307000.0,1245382000.0,1398206000.0
Net Income Continuous Operations,1152891000.0,1886105000.0,1237307000.0,1245382000.0,1398206000.0
Tax Provision,348815000.0,116379000.0,242337000.0,370099000.0,355185000.0
Pretax Income,1501706000.0,2002484000.0,1479644000.0,1615481000.0,1753391000.0
Other Income Expense,110532000.0,516309000.0,196707000.0,234801000.0,137402000.0
Other Non Operating Income Expenses,NaN,NaN,NaN,483000.0,-113000000.0
Special Income Charges,20031000.0,-45791000.0,45791000.0,335000.0,-46126000.0
Gain On Sale Of Ppe,42989000.0,NaN,0.0,NaN,0.0
Gain On Sale Of Business,NaN,NaN,NaN,0.0,NaN
Write Off,22958000.0,45791000.0,-45791000.0,-335000.0,46126000.0
Earnings From Equity Interest,90501000.0,138762000.0,70916000.0,69281000.0,153041000.0
Gain On Sale Of Security,NaN,420850000.0,80000000.0,164702000.0,30487000.0
Net Non Operating Interest Income Expense,-180986000.0,-182721000.0,-295000000.0,-125375000.0,-105914000.0
Total Other Finance Cost,NaN,-25481000.0,13000000.0,77416000.0,10000000.0
Interest Expense Non Operating,399231000.0,158290000.0,282000000.0,263910000.0,435698000.0
Interest Income Non Operating,218245000.0,NaN,NaN,215951000.0,329784000.0
Operating Income,1572160000.0,1669044000.0,1577789000.0,1506055000.0,1721903000.0
Operating Expense,1543100000.0,-52067000.0,1085032000.0,513318000.0,1298703000.0
Other Operating Expenses,708983000.0,-111257000.0,253466000.0,149458000.0,519675000.0
Other Taxes,NaN,NaN,NaN,NaN,43000000.0
Provision For Doubtful Accounts,NaN,NaN,NaN,21266000.0,NaN
Depreciation Amortization Depletion Income Statement,328542000.0,-297044000.0,316693000.0,3943000.0,302666000.0
Depreciation And Amortization In Income Statement,328542000.0,-297044000.0,316693000.0,3943000.0,302666000.0
Selling General And Administration,505575000.0,214217000.0,514873000.0,338651000.0,476362000.0
General And Administrative Expense,505575000.0,214217000.0,514873000.0,338651000.0,476362000.0
Other Gand A,NaN,NaN,NaN,62334000.0,NaN
Salaries And Wages,505575000.0,47803000.0,514873000.0,276317000.0,476362000.0
Gross Profit,3115260000.0,1616977000.0,2662821000.0,2019373000.0,3020606000.0
Cost Of Revenue,5813982000.0,8339940000.0,6763808000.0,6800144000.0,5491565000.0
Total Revenue,8929242000.0,9956917000.0,9426629000.0,8819517000.0,8512171000.0
Excise Taxes,3113468000.0,NaN,NaN,NaN,2221289000.0
Operating Revenue,11379975000.0,12007625000.0,12087629000.0,11041750000.0,10223473000.0

In [16]:
cmig.quarterly_balance_sheet

,2024-03-31,2023-12-31,2023-09-30,2023-06-30,2023-03-31
Treasury Shares Number,1100013.0,1100013.0,NaN,NaN,1100013.0
Ordinary Shares Number,2860681881.0,2860681881.0,2860681881.0,2860681881.0,2860681881.0
Share Issued,2861781894.0,2861781894.0,2860681881.0,2860681881.0,2861781894.0
Net Debt,9449000000.0,8294000000.0,9750000000.0,9648227000.0,8679000000.0
Total Debt,12049000000.0,10264000000.0,12515000000.0,12247119000.0,10685000000.0
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,5403000000.0,3125000000.0,5003000000.0,4503033000.0,3986000000.0
Other Short Term Investments,3226000000.0,1588000000.0,2647000000.0,2320214000.0,2386000000.0
Cash And Cash Equivalents,2177000000.0,1537000000.0,2356000000.0,2182819000.0,1600000000.0
Cash Equivalents,NaN,1342000000.0,NaN,2132061000.0,NaN
Cash Financial,NaN,195000000.0,NaN,50758000.0,NaN